services:
  keycloak:
    container_name: assoc_femme
    image: quay.io/keycloak/keycloak:26.5.1
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: passwordassoc
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - 'start-dev'

volumes:
  keycloak_data: